id: P004253
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3CN2194
  title: གསུང་འབུམ། ལྷ་རྩེ་བ་ངག་དབང་བཟང་པོ།
  author: ''
  volumes:
    51f8b5acd948466389c4501ee270f987:
      image_group_id: I3CN2196
      title: ''
      volume_number: 1
      total_pages: 626
      base_file: v001.txt
    cd0ea09f287b4c5ca478562b3b32b01c:
      image_group_id: I3CN2197
      title: ''
      volume_number: 2
      total_pages: 701
      base_file: v002.txt
