id: I4F47F64F
legacy_id: P004253
ocr_import_info:
  bdrc_scan_id: W3CN2194
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T04:12:20'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T12:27:04.373536+00:00'
last_modified: 2022-09-03 20:27:36.927321
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN2194
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN2194
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ལྷ་རྩེ་བ་ངག་དབང་བཟང་པོ།
  author: བདེ་ཆེན་ཆོས་འཁོར་ཡོངས་འཛིན ༠༡་ངག་དབང་བཟང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.7632507859578203
  ocr_word_median_confidence_index: 0.8399999737739563
quality: null
bases:
  I3CN2197:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN2197
      total_pages: 701
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3CN2197.txt
    statistics:
      ocr_word_median_confidence_index: 0.8399999737739563
      ocr_word_mean_confidence_index: 0.7616300853256642
    legacy_id: v002
  I3CN2196:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN2196
      total_pages: 626
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN2196.txt
    statistics:
      ocr_word_median_confidence_index: 0.8500000238418579
      ocr_word_mean_confidence_index: 0.7655604344441038
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
