id: I4F47F64F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T04:13:48+00:00'
last_modified: '2022-06-07T21:26:16.327172+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN2194
  title: གསུང་འབུམ། ལྷ་རྩེ་བ་ངག་དབང་བཟང་པོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    5FFE:
      image_group_id: I3CN2196
      title: ''
      total_pages: 626
      order: 1
      base_file: 5FFE.txt
    4B3A:
      image_group_id: I3CN2197
      title: ''
      total_pages: 701
      order: 2
      base_file: 4B3A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
